# Generated by Django 3.0.8 on 2020-12-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelledDelivery',
        ),
        migrations.DeleteModel(
            name='ExtraDelivery',
        ),
    ]
