# Generated by Django 3.0.8 on 2020-08-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200816_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='dt_received',
            field=models.DateField(blank=True, null=True, verbose_name='Datetime donation received'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='dt_thanked',
            field=models.DateField(blank=True, null=True, verbose_name='Datetime thanked'),
        ),
    ]
