# Generated by Django 3.0.8 on 2020-11-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200816_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dt_requested_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime requested for delivery.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passphrase',
            field=models.CharField(help_text='Enter a name, word or phrase you can use next time to fill out most of this form for you.', max_length=20, verbose_name='Passphrase'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='schools',
            field=models.ManyToManyField(blank=True, help_text='DContinue clicking to add all schools that apply.', related_name='customers', to='orders.School', verbose_name='Schools'),
        ),
    ]
