# Generated by Django 3.0.8 on 2020-11-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20201120_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dt_requested_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Date requested for delivery.'),
        ),
    ]
