# Generated by Django 3.0.8 on 2020-11-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20201120_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dropoff_location',
        ),
        migrations.DeleteModel(
            name='DropoffLocation',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
