# Generated by Django 3.0.8 on 2020-11-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20201121_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_can_receive_texts',
            field=models.BooleanField(default=False, help_text='Can receive text messages?', verbose_name='Texts?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='secondary_phone_can_receive_texts',
            field=models.BooleanField(default=False, help_text='Can receive text messages?', verbose_name='Texts?'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], default='en', max_length=2, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='schools',
            field=models.ManyToManyField(blank=True, help_text='Continue clicking to add all schools that apply. (MCPS Schools only)', related_name='customers', to='orders.School', verbose_name='MCPS Schools'),
        ),
    ]
