# Generated by Django 3.0.8 on 2020-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20201123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='secondary_phone_can_receive_texts',
            field=models.BooleanField(default=False, help_text='Secondary Phone can receive text messages?', verbose_name='Texts?'),
        ),
    ]
