# Generated by Django 3.0.8 on 2020-11-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20201124_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_zip',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
