# Generated by Django 3.0.8 on 2020-11-30 11:36

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('orders', '0013_order_customer_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
    ]
