# Generated by Django 3.0.8 on 2020-11-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20201130_0636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-dt_updated'], 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='dt_delivered',
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Delivery is open or closed?'),
        ),
    ]
