# Generated by Django 3.0.8 on 2020-12-01 18:29

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20201201_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime updated')),
                ('title', models.CharField(max_length=254)),
                ('body', djrichtextfield.models.RichTextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
