# Generated by Django 3.0.8 on 2020-12-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20201202_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
