# Generated by Django 3.0.8 on 2020-12-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Datetime updated')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='supporter',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
