# Generated by Django 3.0.8 on 2020-12-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20201207_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryday',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
