# Generated by Django 3.0.8 on 2020-12-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20201207_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryday',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
