# Generated by Django 3.0.8 on 2020-12-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20201207_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryday',
            old_name='date',
            new_name='dt',
        ),
    ]
