# Generated by Django 3.0.8 on 2020-12-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20201207_0824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryDay',
        ),
    ]
