# Generated by Django 3.0.8 on 2020-12-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20201207_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryday',
            options={'ordering': ['_date']},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
