# Generated by Django 3.0.8 on 2020-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryday',
            name='_week',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
