# Generated by Django 3.0.8 on 2020-12-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_deliveryday__week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryday',
            old_name='_week',
            new_name='_week_of_year',
        ),
    ]
