# Generated by Django 3.0.8 on 2020-12-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20201208_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default='', verbose_name='Notes'),
        ),
    ]
