# Generated by Django 3.0.8 on 2020-12-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20201208_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quick_note',
            field=models.CharField(blank=True, default=True, max_length=255, verbose_name='Quick Note'),
        ),
    ]
