# Generated by Django 3.0.8 on 2020-12-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_quick_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(default='Notes:', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quick_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Quick Note'),
        ),
    ]
