# Generated by Django 3.0.8 on 2020-12-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20201208_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryday',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
