# Generated by Django 3.0.8 on 2020-12-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_deliveryday_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
