# Generated by Django 3.0.8 on 2020-12-11 16:26

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('orders', '0039_deliveryday_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='address.Address', verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='orders.Supporter'),
        ),
    ]
