# Generated by Django 3.1.5 on 2021-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20201211_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='can_drive',
            field=models.BooleanField(default=False, help_text='Is willing to drive.'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='is_driver',
            field=models.BooleanField(default=False, help_text='Is currently actively driving.'),
        ),
    ]
